import { Breed } from "../../classes/Breed";

var breed: Breed 



export var dogBreed = [
'Afghan Hound',
'Airedale Terrier',
'Akita',
'Alaskan Malamute',
'American Eskimo Dog',
'American Foxhound',
'American Staffordshire Terrier',
'American Water Spaniel',
'Anatolian Shepherd',
'Australian Cattle Dog',
'Australian Kelpie',
'Australian Shepherd',
'Australian Terrier',
'Affenpinscher',
'Basenji',
'Basset Hound',
'Beagle',
'Bearded Collie',
'Bedlington Terrier',
'Belgian Malinois',
'Belgian Sheepdog',
'Belgian Tervuren',
'Bernese Mountain Dog',
'Bichon Frise',
'Black and Tan Coonhound',
'Bloodhound',
'Border Collie',
'Border Terrier',
'Borzol',
'Boston Terrier',
'Bouvier des Flandres',
'Boxer',
'Briard',
'Brittany',
'Brussels Griffon',
'Bull Terrier',
'Bulldog',
'Bullmastiff',
'Cairn Terrier',
'Canaan Dog',
'Cardigan Welsh Corgi',
'Cavalier King Charles Spaniel',
'Chesapeake Bay Retriever',
'Chihuahua',
'Chinese Crested',
'Chinese Shar-Pei',
'Chow Chow',
'Clumber Spaniel',
'Cocker Spaniel',
'Collie',
'Curly-Coated Retriever',
'Dachshund',
'Dalmatian',
'Dandle Dinmont Terrier',
'Doberman Pinscher',
'English Cocker Spaniel',
'English Foxhound',
'English Setter',
'English Springer Spaniel',
'English Toy Spaniel',
'Field Spaniel',
'Finnish Spitz',
'Flat-Coated Retriever',
'French Bulldog',
'German Pinscher',
'German Shepherd Dog',
'German Shorthaired Pointer',
'German Wirehaired Pointer',
'Giant Schnauzer',
'Golden Retriever',
'Gordon Setter',
'Great Dane',
'Great Pyrenees',
'Greater Swiss Mountain Dog',
'Greyhound',
'Harrier',
'Havanese',
'Ibizan Hound',
'Irish Setter',
'Irish Terrier',
'Irish Water Spaniel',
'Irish Wolfhound',
'Italian Greyhound',
'Jack Russell Terrier',
'Japanese Chin',
'Keeshond',
'Kerry Blue Terrier',
'Komondor',
'Kuvasz',
'Labrador Retriever',
'Lakeland Terrier',
'Lhasa Apso',
'Lowchen'
]